config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "homepage#home", as: "root"
  get 'team_builder/start'
  get 'team_builder/generate'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def home
  end
end

app/controllers/team_builder_controller.rb
class TeamBuilderController < ApplicationController
  def start
    @players = Player.all
  end

  def generate
    players = Player.all
    @list = players.sample(28).sort!.reverse!
    @team_four = []
    @team_three = []
    @team_two = []
    @team_one = []
    @team_one << @list.pop
    @team_two << @list.pop
    @team_three << @list.pop
    @team_four << @list.pop
    @team_four << @list.pop
    @team_three << @list.pop
    @team_two << @list.pop
    @team_one << @list.pop
    @team_one << @list.pop
    @team_two << @list.pop
    @team_three << @list.pop
    @team_four << @list.pop
    @team_four << @list.pop
    @team_three << @list.pop
    @team_two << @list.pop
    @team_one << @list.pop
    @team_one << @list.pop
    @team_two << @list.pop
    @team_three << @list.pop
    @team_four << @list.pop
    @team_four << @list.pop
    @team_three << @list.pop
    @team_two << @list.pop
    @team_one << @list.pop
    @team_one << @list.pop
    @team_two << @list.pop
    @team_three << @list.pop
    @team_four << @list.pop

    @four_total = 0
    @team_four.each do |player|
      @four_total += player.war
    end
    @three_total = 0
    @team_three.each do |player|
      @three_total += player.war
    end
    @two_total = 0
    @team_two.each do |player|
      @two_total += player.war
    end
    @one_total = 0
    @team_one.each do |player|
      @one_total += player.war
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/team_builder_helper.rb
module TeamBuilderHelper
end

app/views/homepage/home.html.erb
  <section id="intro" style="background-image: url('img/ein-steig.jpg');" class="intro">
      <div class="overlay"></div>
      <div class="content">
        <div class="container clearfix">
          <div class="row">
            <div class="col-lg-8 col-md-12 mx-auto">
              <h1>Hi Kate</h1>
              <p class="italic">It's not much, but it's a start.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- intro end-->
    <!-- navbar-->
    <header class="header">
      <nav class="navbar navbar-expand-lg">
        <div class="container"><a href="#intro" class="navbar-brand link-scroll"><img src="img/logo.png" alt="" class="img-fluid"></a>
          <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler navbar-toggler-right"><i class="fa fa-bars"></i></button>
          <div id="navbarSupportedContent" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><%= link_to "Team Builder", team_builder_start_path, class: "btn btn-primary" %></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <!-- about-->
    <!-- text page-->
    <section id="text" class="text-page section-inverse">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h2 class="heading">A Story</h2>
            <div class="row">
              <div class="col-md-6">
                <p>There will eventually be a story here. For now you have to be happy with the baffling beauty of this placeholder text.</p>
                <p>Betrayed cheerful declared end and. Questions we additions is extremely incommode. Next half add call them eat face. Age lived smile six defer bed their few. Had admitting concluded too behaviour him she. Of death to or to being other. </p>
              </div>
              <div class="col-md-6">
                <p>Effects present letters inquiry no an removed or friends. Desire behind latter me though in. Supposing shameless am he engrossed up additions. My possible peculiar together to. Desire so better am cannot he up before points. Remember mistaken opinions it pleasure of debating. Court front maids forty if aware their at. Chicken use are pressed removed. </p>
                <p>Saw yet kindness too replying whatever marianne. Old sentiments resolution admiration unaffected its mrs literature. Behaviour new set existence dashwoods. It satisfied to mr commanded consisted disposing engrossed. Tall snug do of till on easy. Form not calm new fail. </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- text page end-->

    <!-- JavaScript files-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="vendor/lightbox2/js/lightbox.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.4.0/leaflet.js"> </script>
    <script src="js/front.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/team_builder/generate.html.erb
<h1>TeamBuilder#generate</h1>

<% @list.each do |player|  %>
  <%= player.name %>
  <%= player.war %>
<% end %>
<h3>Team 1</h3>
<% @team_one.each do |player|  %>
  <%= player.name %>
  <%= player.war %>
<% end %>
<b>Team total: <%= @one_total %></b>
<h3>Team 2</h3>
<% @team_two.each do |player|  %>
  <%= player.name %>
  <%= player.war %>
<% end %>
<b>Team total: <%= @two_total %></b>
<h3>Team 3</h3>
<% @team_three.each do |player|  %>
  <%= player.name %>
  <%= player.war %>
<% end %>
<b>Team total: <%= @three_total %></b>
<h3>Team 4</h3>
<% @team_four.each do |player|  %>
  <%= player.name %>
  <%= player.war %>
<% end %>
<b>Team total: <%= @four_total %></b>

app/views/team_builder/start.html.erb
<h1>TeamBuilder#start</h1>
<%= link_to "Generate a random 28 people and 4 teams from them", team_builder_generate_path, class: "btn btn-primary" %>

<% @players.each do |player|  %>
  <%= player.name %>
  <%= player.war %>
  <br>
<% end %>